version: '3.8'

volumes:
  prometheus_data: {}
  grafana_data: {}

networks:
  lunatech-net:

services:
  lunatech-candy:
    image: com.lunatech/lunatech-traces-metrics-exemplars:v0.0.1
    ports:
      - 13798:13798 #prometheus
    networks:
      - lunatech-net

  tempo:
    image: grafana/tempo:1.2.1
    command:
      - --target=all
      - --storage.trace.backend=local
      - --storage.trace.local.path=/var/tempo
      - --compactor.compaction.block-retention=24h
      - --distributor.log-received-traces
      - --config.file=/etc/tempo.yaml
    volumes:
      - ./tempo/tempo-local.yaml:/etc/tempo.yaml
    ports:
      - 3200:3200    # tempo
      - 55680:55680  # otlp grpc
    networks:
      - lunatech-net

  # OpenTelemetry Collector
  otel-collector:
    image: otel/opentelemetry-collector:0.41.0
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./otel/otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - ./otel/output:/etc/otel/output:rw # Store the logs
    ports:
      - 8888:8888   # Prometheus metrics exposed by the collector
      - 8889:8889   # Prometheus exporter metrics
      - 4317:4317   # OTLP gRPC receiver
    networks:
      - lunatech-net

  prometheus:
    image: prom/prometheus:v2.31.1
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--enable-feature=exemplar-storage'
    ports:
      - 9090:9090
    links:
      - lunatech-candy:lunatech-candy
      - otel-collector
    depends_on:
      - lunatech-candy
    networks:
      - lunatech-net

  grafana:
    image: grafana/grafana:8.3.3
    depends_on:
      - prometheus
      - tempo
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    networks:
      - lunatech-net
